"""change note vector size to 768

Revision ID: 3e77b996ea9f
Revises: cc1f916e0219
Create Date: 2025-07-04 16:26:01.603470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '3e77b996ea9f'
down_revision: Union[str, Sequence[str], None] = 'cc1f916e0219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note', 'vector',
               existing_type=sa.dialects.postgresql.BYTEA(),
               type_=Vector(768),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note', 'vector',
               existing_type=Vector(768),
               type_=sa.dialects.postgresql.BYTEA(),
               existing_nullable=True)
    # ### end Alembic commands ###
