"""add_essay_analysis_models

Revision ID: 99bee704f4fa
Revises: bda96fdc12e8
Create Date: 2025-07-12 16:03:24.265019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99bee704f4fa'
down_revision: Union[str, Sequence[str], None] = 'bda96fdc12e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_note_folder_owner', 'note', ['folder_id', 'owner_id'], unique=False)
    op.create_index('idx_note_owner_created', 'note', ['owner_id', 'created_at'], unique=False)
    op.create_index('idx_note_owner_due', 'note', ['owner_id', 'due'], unique=False)
    op.create_index('idx_note_owner_state', 'note', ['owner_id', 'state'], unique=False)
    op.create_index('idx_note_owner_type', 'note', ['owner_id', 'type'], unique=False)
    op.create_index('idx_practice_list_owner_updated', 'practicelist', ['owner_id', 'updated_at'], unique=False)
    op.create_index('idx_practice_list_item_order', 'practicelistitem', ['practice_list_id', 'order_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_practice_list_item_order', table_name='practicelistitem')
    op.drop_index('idx_practice_list_owner_updated', table_name='practicelist')
    op.drop_index('idx_note_owner_type', table_name='note')
    op.drop_index('idx_note_owner_state', table_name='note')
    op.drop_index('idx_note_owner_due', table_name='note')
    op.drop_index('idx_note_owner_created', table_name='note')
    op.drop_index('idx_note_folder_owner', table_name='note')
    # ### end Alembic commands ###
