"""add_practice_list_models

Revision ID: bda96fdc12e8
Revises: 96d68f4f4226
Create Date: 2025-07-06 18:29:06.520250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda96fdc12e8'
down_revision: Union[str, Sequence[str], None] = '96d68f4f4226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_corrected_text_trgm'), table_name='note', postgresql_using='gin')
    op.drop_index(op.f('ix_note_folder_id'), table_name='note')
    op.drop_index(op.f('ix_note_owner_id'), table_name='note')
    op.drop_index(op.f('ix_note_text_trgm'), table_name='note', postgresql_using='gin')
    op.drop_index(op.f('ix_note_translation_gin'), table_name='note', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_note_translation_gin'), 'note', [sa.literal_column('(translation::jsonb)')], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_note_text_trgm'), 'note', ['text'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_note_owner_id'), 'note', ['owner_id'], unique=False)
    op.create_index(op.f('ix_note_folder_id'), 'note', ['folder_id'], unique=False)
    op.create_index(op.f('ix_note_corrected_text_trgm'), 'note', ['corrected_text'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
