"""add search performance indexes

Revision ID: bf1ab2092ce2
Revises: c3fbabcb4e97
Create Date: 2025-07-05 21:18:48.068176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bf1ab2092ce2'
down_revision: Union[str, None] = 'c3fbabcb4e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')
    op.create_index('ix_note_text_trgm', 'note', ['text'], unique=False, postgresql_using='gin', postgresql_ops={'text': 'gin_trgm_ops'})
    op.create_index('ix_note_corrected_text_trgm', 'note', ['corrected_text'], unique=False, postgresql_using='gin', postgresql_ops={'corrected_text': 'gin_trgm_ops'})
    op.create_index('ix_note_translation_gin', 'note', ['translation'], unique=False, postgresql_using='gin', postgresql_ops={'translation': 'jsonb_path_ops'})
    op.create_index(op.f('ix_note_folder_id'), 'note', ['folder_id'], unique=False)
    op.create_index(op.f('ix_note_owner_id'), 'note', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_owner_id'), table_name='note')
    op.drop_index(op.f('ix_note_folder_id'), table_name='note')
    op.drop_index('ix_note_translation_gin', table_name='note', postgresql_using='gin')
    op.drop_index('ix_note_corrected_text_trgm', table_name='note')
    op.drop_index('ix_note_text_trgm', table_name='note')
    op.execute('DROP EXTENSION IF EXISTS pg_trgm;')
    # ### end Alembic commands ###
