name: Test Docker Build and Services

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test-docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file for API (Manual)
        run: |
          echo '${{ toJSON(secrets) }}' | jq -r 'to_entries[] | select(.key | startswith("API_")) | "\(.key | ltrimstr("API_"))=\(.value)"' > apps/api/.env

      - name: Create .env file for Web (Manual)
        run: |
          echo '${{ toJSON(secrets) }}' | jq -r 'to_entries[] | select(.key | startswith("WEB_")) | "\(.key | ltrimstr("WEB_"))=\(.value)"' > apps/web/.env

      - name: Build docker images
        run: docker compose build

      - name: Run services in background
        run: docker compose up -d api web

      - name: Display API service logs for debugging
        run: docker compose logs api

      - name: Test API service is up
        run: curl --fail http://localhost:8000/

      - name: Test Web service is up
        run: curl --fail http://localhost:3000/
      
      - name: Tear down services
        run: docker compose down -v --remove-orphans