name: Test Docker Build and Services

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test-docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build docker images
        run: docker compose build

      - name: Run services in background
        run: docker compose up -d api web db

      - name: Wait for services to start
        run: sleep 10

      - name: Test API service is up
        run: curl --fail http://localhost:8000/

      - name: Test Web service is up
        run: curl --fail http://localhost:3000/
      
      - name: Tear down services
        run: docker compose down -v --remove-orphans