name: Test Docker Build and Services

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test-docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file for API (Manual)
        run: |
          echo '${{ toJSON(secrets) }}' | jq -r 'to_entries[] | select(.key | startswith("API_")) | "\(.key | ltrimstr("API_"))=\(.value)"' > apps/api/.env

      - name: Create .env file for Web (Manual)
        run: |
          echo '${{ toJSON(secrets) }}' | jq -r 'to_entries[] | select(.key | startswith("WEB_")) | "\(.key | ltrimstr("WEB_"))=\(.value)"' > apps/web/.env

      - name: Build docker images
        run: docker compose build